#!/bin/sh

##############
#INTRODUCTION#
##############

#This is just the original version of the code to create indexed files 
#with bcftools.

#We need the index files to be able to generate the plink data that we 
#can later use with R.

######
#MAIN#
######

cd ~/RAW_DATA/VCF_DATA

for i in {1..22}; do
   bcftools index --tbi ALL.chr${i}.phase3_v5.shapeit2_mvncall_integrated.noSingleton.genotypes.vcf.gz
done

#########
#PERFECT#
#########






