#!/bin/sh

##############
#INTRODUCTION#
##############

#This is just the original version of the code to create symbolic links for the 1000G Phase3 version 5 data.
#with bcftools.

#We need the index files to be able to generate the plink data that we 
#can later use with R.

######
#MAIN#
######
for i in {1..22}; do
    ln  -s /emc/cbmr/data/imputed/1kgphase3_v5/ALL.chr${i}.phase3_v5.shapeit2_mvncall_integrated.noSingleton.genotypes.vcf.gz .
done

#########
#PERFECT#
#########







